# Generated by Django 5.1.1 on 2024-10-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Ingles'), ('Frances', 'FR'), ('IT', 'Italiano')], default='ES', max_length=200),
        ),
    ]
